package com.utils;

public enum NetworkRequestName {
	LOGIN,
	REGISTER,
	HOMESLIDER,
	RWAS,
	RWAS_DTEAIL,
	RWAS_FACILITY,
	GROUPS,
	CREATE_GROUPS,
	GROUPS_DETAIL,
	SERVICES,
	SERVICES_DETAIL,
	REQUEST_SERVICES,
	SERVICES_REQUEST_STATUS,
	SERVICES_DELETE,
	BOOKINGS,
	NOTICEBOARDS,
	NOTICEBOARDS_DETAILS,
	DIRECTORY,
	SPIDYPICKS,
	SPIDYPICKS_DETAILS,
	OPINIONPOLLS,
	OPINIONPOLLS_DETAILS,
	OPINIONPOLLS_VOTE;
}
